apiVersion: apps/v1
kind: Deployment
metadata:
  name: proxy-deployment
  labels:
    app: proxy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: proxy
  template:
    metadata:
      labels:
        app: proxy
    spec:
      containers:
      - name: proxy
        image: vancoricomplex/proxy-test:v1
        ports:
        - containerPort: 80
        env:
        - name: API_HOST
          valueFrom:
            configMapKeyRef:
              name: home-jungle-config
              key: api-host
        - name: API_PORT
          valueFrom:
            configMapKeyRef:
              name: home-jungle-config
              key: api-port
        - name: CLIENT_HOST
          valueFrom:
            configMapKeyRef:
              name: home-jungle-config
              key: client-host
        - name: CLIENT_PORT
          valueFrom:
            configMapKeyRef:
              name: home-jungle-config
              key: client-port
---
apiVersion: v1
kind: Service
metadata:
  name: proxy-service
spec:
  type: NodePort
  selector:
    app: proxy
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30000