server:
  error:
    include-message: always
spring:
  main:
    banner-mode: off
  datasource:
    url: ${POSTGRES_URL}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: 'update'
  flyway:
    locations: 'classpath:db-flyway-migration/postgres'
  mail:
    host: ${MAIL_HOST}
    port: ${MAIL_PORT}
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          connectiontimeout: 5000
          timeout: 3000
          writetimeout: 5000
  rabbitmq:
    host: ${RABBITMQ_HOST:localhost}
  cache:
    jcache:
      config: 'classpath:ehcache.xml'
# Bucket4j config
bucket4j:
  enabled: true
  filters:
    - cache-name: buckets
      url: .*
      rate-limits:
        - bandwidths:
            - capacity: 5
              time: 1
              unit: seconds
app:
  user-registration:
    # confirmation token expiration time = 30 min
    confirmation-token-expiration-time-min: 30
  security:
    jwt:
      # access token expiration time = 5 min
      access-token-expiration-time-millis: 300000
      # refresh token expiration time = 15 min
      refresh-token-expiration-time-millis: 900000
      secret: ${random.value}
  gcloud:
    project-id: ${GCLOUD_PROJECT_ID}
    storage-base-uri: ${GCLOUD_STORAGE_BASE_URI}
    bucket-name: ${GCLOUD_BUCKET_NAME}
  domain:
    uri-prefix: ${DOMAIN_URI_PREFIX}
    name: ${DOMAIN_NAME}