spring:
  main:
    banner-mode: off
  datasource:
    url: ${POSTGRES_URL:jdbc:postgresql://localhost:5433/home-jungle}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: 'update'
  flyway:
    locations: 'classpath:db-flyway-migration/postgres'
  mail:
    host: ${MAIL_HOST}
    port: ${MAIL_PORT}
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          connectiontimeout: 5000
          timeout: 3000
          writetimeout: 5000
  rabbitmq:
    host: ${RABBITMQ_HOST:localhost}
server:
  error:
    include-message: always
# JWT
# access token expiration time = 5 min
# refresh token expiration time = 15 min
app:
  security:
    jwt:
      access-token-expiration-time-millis: 300000
      refresh-token-expiration-time-millis: 900000
      secret: ${random.value}