apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
  labels:
    app: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: vancoricomplex/home-jungle-backend-prod:0.2.1
        ports:
        - containerPort: 8080
        env:
        - name: DOMAIN_URI_PREFIX
          valueFrom:
            configMapKeyRef:
              name: home-jungle-config
              key: domain-uri-prefix
        - name: DOMAIN_NAME
          valueFrom:
            configMapKeyRef:
              name: home-jungle-config
              key: domain-name
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: home-jungle-secrets
              key: postgres-user
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: home-jungle-secrets
              key: postgres-password
        - name: POSTGRES_URL
          valueFrom:
            secretKeyRef:
              name: home-jungle-secrets
              key: postgres-url
        - name: RABBITMQ_HOST
          valueFrom:
            configMapKeyRef:
              name: home-jungle-config
              key: rabbitmq-host
        - name: MAIL_HOST
          valueFrom:
            secretKeyRef:
              name: home-jungle-secrets
              key: mail-host
        - name: MAIL_PORT
          valueFrom:
            secretKeyRef:
              name: home-jungle-secrets
              key: mail-port
        - name: MAIL_USERNAME
          valueFrom:
            secretKeyRef:
              name: home-jungle-secrets
              key: mail-username
        - name: MAIL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: home-jungle-secrets
              key: mail-password
        - name: GCLOUD_PROJECT_ID
          valueFrom:
            secretKeyRef:
              name: home-jungle-secrets
              key: gcloud-project-id
        - name: GCLOUD_BUCKET_NAME
          valueFrom:
            secretKeyRef:
              name: home-jungle-secrets
              key: gcloud-bucket-name
        - name: GOOGLE_APPLICATION_CREDENTIALS
          valueFrom:
            configMapKeyRef:
              name: home-jungle-config
              key: google-application-credentials
        - name: GCLOUD_SIGN_URL_DURATION_DAYS
          valueFrom:
            configMapKeyRef:
              name: home-jungle-config
              key: gcloud-sign-url-duration-days
---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
spec:
  selector:
    app: backend
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080